### ISSUE TITLE
For Test only

### ISSUE THREAD

**Issue by hwndept** [tcm-labs/workflow#18]
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`
- tests v`

**Comment by nelsonic** [comment]
What happens on the GitHub Board: https://github.com/orgs/tcm-labs/projects/1?fullscreen=true 
when an issue is _closed_?
